/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// Helper to generate IDs
const generateId = () => Math.random().toString(36).substr(2, 9);

export const initialEPCPartners = [
  {
    id: "epc-1",
    partnerName: "Vikram Solar Solutions",
    companyName: "Vikram Solar Pvt Ltd",
    email: "contact@vikramsolar.com",
    mobile: "+91 98765 43210",
    hqLocation: "Kolkata",
    state: "West Bengal",
    district: "Kolkata",
    cluster: "East Cluster-A",
    experience: 12,
    projectTypes: ["Residential", "Commercial", "Industrial"],
    minKW: 5,
    maxKW: 500,
    installersCount: 24,
    status: "Active",
    rating: 4.8,
    subscriptionPlan: "Premium Plan",
    kycStatus: "Approved",
    agreementStatus: "Signed",
    kycDetails: {
      companyRegNo: "U40106WB2008PTC123456",
      gstNumber: "19AAACV4829N1Z5",
      panNumber: "AAACV4829N",
      addressProofUrl: "company_address.pdf",
      bankName: "State Bank of India",
      accountNo: "30291039871",
      ifscCode: "SBIN0000001",
      cancelledChequeUrl: "cancelled_cheque.jpg",
      authPersonName: "Vikram Sharan",
      authPersonEmail: "vsharan@vikramsolar.com",
      authPersonMobile: "+91 98765 43211",
      authPersonDesignation: "Managing Director",
      authPersonIdUrl: "vikram_id.pdf",
      digitalAgreementUrl: "agreement_signed.pdf",
      undertakingChecked: true,
      agreementAcceptedDate: "2026-01-15",
    },
  },
  {
    id: "epc-2",
    partnerName: "Waaree Green Energy",
    companyName: "Waaree Energies Ltd",
    email: "support@waaree.co.in",
    mobile: "+91 91234 56789",
    hqLocation: "Mumbai",
    state: "Maharashtra",
    district: "Mumbai Suburban",
    cluster: "West Cluster-B",
    experience: 15,
    projectTypes: ["Commercial", "Industrial", "Utility Scale"],
    minKW: 50,
    maxKW: 5000,
    installersCount: 45,
    status: "Active",
    rating: 4.9,
    subscriptionPlan: "Enterprise Plan",
    kycStatus: "Approved",
    agreementStatus: "Signed",
    kycDetails: {
      companyRegNo: "U40108MH1999PLC098234",
      gstNumber: "27AAACW9912A1ZX",
      panNumber: "AAACW9912A",
      addressProofUrl: "waaree_reg.pdf",
      bankName: "HDFC Bank",
      accountNo: "501000234012",
      ifscCode: "HDFC0000060",
      cancelledChequeUrl: "cheque_img.png",
      authPersonName: "Hitesh Doshi",
      authPersonEmail: "hdoshi@waaree.co.in",
      authPersonMobile: "+91 91234 56780",
      authPersonDesignation: "Chairman & CEO",
      authPersonIdUrl: "hitesh_pan.pdf",
      digitalAgreementUrl: "waaree_agreement.pdf",
      undertakingChecked: true,
      agreementAcceptedDate: "2026-02-10",
    },
  },
  {
    id: "epc-3",
    partnerName: "SunSpark Renewable Co.",
    companyName: "SunSpark Energies LLP",
    email: "info@sunspark.in",
    mobile: "+91 88877 66554",
    hqLocation: "Pune",
    state: "Maharashtra",
    district: "Pune",
    cluster: "West Cluster-C",
    experience: 4,
    projectTypes: ["Residential", "Commercial"],
    minKW: 2,
    maxKW: 100,
    installersCount: 8,
    status: "Pending",
    rating: 4.2,
    subscriptionPlan: "Starter Plan",
    kycStatus: "Pending",
    agreementStatus: "Pending",
    kycDetails: {
      companyRegNo: "AAH-8910",
      gstNumber: "27AABCS9821R2ZY",
      panNumber: "AABCS9821R",
      addressProofUrl: "rent_agreement_pune.pdf",
      bankName: "ICICI Bank",
      accountNo: "000401567210",
      ifscCode: "ICIC0000004",
      cancelledChequeUrl: "cheque_pune.pdf",
      authPersonName: "Anil Deshmukh",
      authPersonEmail: "adeshmukh@sunspark.in",
      authPersonMobile: "+91 88877 66551",
      authPersonDesignation: "Partner",
      authPersonIdUrl: "anil_aadhaar.pdf",
      undertakingChecked: true,
      adminRemarks: "Pending physical document verification",
    },
  },
  {
    id: "epc-4",
    partnerName: "Renewable Power Point",
    companyName: "PowerPoint Green Ltd",
    email: "epc@powerpoint.com",
    mobile: "+91 77766 55544",
    hqLocation: "Bengaluru",
    state: "Karnataka",
    district: "Bengaluru Urban",
    cluster: "South Cluster-A",
    experience: 6,
    projectTypes: ["Residential", "Commercial"],
    minKW: 3,
    maxKW: 250,
    installersCount: 12,
    status: "Active",
    rating: 4.5,
    subscriptionPlan: "Growth Plan",
    kycStatus: "Approved",
    agreementStatus: "Signed",
    kycDetails: {
      companyRegNo: "U31900KA2015PTC085231",
      gstNumber: "29AAACP1283M1ZN",
      panNumber: "AAACP1283M",
      addressProofUrl: "electric_bill.pdf",
      bankName: "Axis Bank",
      accountNo: "915020087612345",
      ifscCode: "UTIB0000009",
      cancelledChequeUrl: "axis_cheque.jpg",
      authPersonName: "Sanjay Hegde",
      authPersonEmail: "shegde@powerpoint.com",
      authPersonMobile: "+91 77766 55541",
      authPersonDesignation: "Director Of Operations",
      authPersonIdUrl: "sanjay_id.pdf",
      digitalAgreementUrl: "rpp_agreement.pdf",
      undertakingChecked: true,
      agreementAcceptedDate: "2026-03-01",
    },
  },
  {
    id: "epc-5",
    partnerName: "Solon Solar Infrastructure",
    companyName: "Solon Infra Private Limited",
    email: "info@soloninfra.com",
    mobile: "+91 99887 76655",
    hqLocation: "Jaipur",
    state: "Rajasthan",
    district: "Jaipur",
    cluster: "North Cluster-D",
    experience: 8,
    projectTypes: ["Commercial", "Industrial", "Utility Scale"],
    minKW: 30,
    maxKW: 1000,
    installersCount: 18,
    status: "Suspended",
    rating: 3.9,
    subscriptionPlan: "Growth Plan",
    kycStatus: "Approved",
    agreementStatus: "Expired",
    kycDetails: {
      companyRegNo: "U45201RJ2012PTC039234",
      gstNumber: "08AAACS1234F1ZA",
      panNumber: "AAACS1234F",
      addressProofUrl: "solon_gst.pdf",
      bankName: "Kotak Mahindra Bank",
      accountNo: "7829102871",
      ifscCode: "KKBK0000120",
      cancelledChequeUrl: "cheque_solon.pdf",
      authPersonName: "Rajendra Singh",
      authPersonEmail: "rsingh@soloninfra.com",
      authPersonMobile: "+91 99887 76650",
      authPersonDesignation: "Proprietor",
      authPersonIdUrl: "raj_pan.pdf",
      digitalAgreementUrl: "solon_agreement_2024.pdf",
      undertakingChecked: true,
      agreementAcceptedDate: "2024-05-15",
      adminRemarks:
        "Agreement expired on 2025-05-14. Suspended until fresh validation.",
    },
  },
  {
    id: "epc-6",
    partnerName: "Ganga Solar Utilities",
    companyName: "Ganga Solar Solutions LLP",
    email: "gangasolar@gmail.com",
    mobile: "+91 87654 32109",
    hqLocation: "Varanasi",
    state: "Uttar Pradesh",
    district: "Varanasi",
    cluster: "Central Cluster-C",
    experience: 3,
    projectTypes: ["Residential"],
    minKW: 1,
    maxKW: 50,
    installersCount: 5,
    status: "Pending",
    rating: 4.0,
    subscriptionPlan: "Starter Plan",
    kycStatus: "Pending",
    agreementStatus: "Not Sent",
    kycDetails: {
      companyRegNo: "AAN-2910",
      gstNumber: "09AAAFG8291A1ZK",
      panNumber: "AAAFG8291A",
      addressProofUrl: "voters_id_doc.pdf",
      bankName: "Punjab National Bank",
      accountNo: "0420000123984",
      ifscCode: "PUNB0042000",
      cancelledChequeUrl: "pnb_cheque.jpg",
      authPersonName: "Shambhu Nath Ganga",
      authPersonEmail: "snganga@gangasolar.com",
      authPersonMobile: "+91 87654 32100",
      authPersonDesignation: "Chief Partner",
      authPersonIdUrl: "shambhu_id.pdf",
      undertakingChecked: true,
      adminRemarks: "Pending tax-clearance audit review",
    },
  },
];

export const initialQualificationRules = [
  {
    id: "rule-1",
    partnerType: "New EPC Partner",
    minExperienceYears: 1,
    projectType: "Residential",
    minKW: 1,
    maxKW: 20,
    hqLocation: "All",
    state: "All",
    district: "All",
    cluster: "All",
    minInstallersRequired: 2,
    maxProjectsPerMonth: 3,
    isActive: true,
  },
  {
    id: "rule-2",
    partnerType: "Experienced EPC Partner",
    minExperienceYears: 3,
    projectType: "Residential, Commercial",
    minKW: 10,
    maxKW: 150,
    hqLocation: "All",
    state: "All",
    district: "All",
    cluster: "All",
    minInstallersRequired: 5,
    maxProjectsPerMonth: 10,
    isActive: true,
  },
  {
    id: "rule-3",
    partnerType: "Premium EPC Partner",
    minExperienceYears: 5,
    projectType: "Residential, Commercial, Industrial",
    minKW: 50,
    maxKW: 500,
    hqLocation: "Tier 1 Cities",
    state: "All",
    district: "All",
    cluster: "All",
    minInstallersRequired: 10,
    maxProjectsPerMonth: 25,
    isActive: true,
  },
  {
    id: "rule-4",
    partnerType: "Large Scale EPC Partner",
    minExperienceYears: 8,
    projectType: "Industrial, Utility Scale",
    minKW: 250,
    maxKW: 10000,
    hqLocation: "Metros",
    state: "Maharashtra, Karnataka, Gujarat",
    district: "All",
    cluster: "Industrial Zones",
    minInstallersRequired: 25,
    maxProjectsPerMonth: 100,
    isActive: true,
  },
];

export const subscriptionPlans = [
  {
    id: "plan-1",
    planName: "Starter Plan",
    monthlyPrice: 149,
    allowedRegions: ["Single State (HQ State)"],
    allowedProjectTypes: ["Residential"],
    projectsAcceptedPerMonth: 5,
    installerLimit: 4,
    projectManagementAccess: true,
    installerAppAccess: false,
    ratingBenefits: false,
    priorityProjectAssignment: false,
    status: "Active",
  },
  {
    id: "plan-2",
    planName: "Growth Plan",
    monthlyPrice: 349,
    allowedRegions: ["Multi-State (Up to 3 States)"],
    allowedProjectTypes: ["Residential", "Commercial"],
    projectsAcceptedPerMonth: 20,
    installerLimit: 12,
    projectManagementAccess: true,
    installerAppAccess: true,
    ratingBenefits: true,
    priorityProjectAssignment: false,
    status: "Active",
  },
  {
    id: "plan-3",
    planName: "Premium Plan",
    monthlyPrice: 699,
    allowedRegions: ["All States / Nationwide"],
    allowedProjectTypes: ["Residential", "Commercial", "Industrial"],
    projectsAcceptedPerMonth: 60,
    installerLimit: 30,
    projectManagementAccess: true,
    installerAppAccess: true,
    ratingBenefits: true,
    priorityProjectAssignment: true,
    status: "Active",
  },
  {
    id: "plan-4",
    planName: "Enterprise Plan",
    monthlyPrice: 1299,
    allowedRegions: ["Nationwide (Priority High-Load Clusters)"],
    allowedProjectTypes: [
      "Residential",
      "Commercial",
      "Industrial",
      "Utility Scale",
    ],
    projectsAcceptedPerMonth: 999, // Unlimited
    installerLimit: 100,
    projectManagementAccess: true,
    installerAppAccess: true,
    ratingBenefits: true,
    priorityProjectAssignment: true,
    status: "Active",
  },
];

export const initialProjects = [
  {
    id: "proj-1",
    projectName: "Skyline Mall Commercial Solar Grid",
    customerName: "Skyline Group Retail Ltd",
    projectType: "Commercial",
    kwSize: 150,
    location: "Sakinaka, Mumbai",
    state: "Maharashtra",
    district: "Mumbai Suburban",
    cluster: "West Cluster-B",
    installationAddress: "Sakinaka Junction, Metro Pillar 78, Mumbai 400072",
    assignedEPCPartnerId: "epc-2",
    assignedEPCPartnerName: "Waaree Green Energy",
    assignedInstallerId: "inst-3",
    assignedInstallerName: "Karan Patil",
    startDate: "2026-05-01",
    expectedCompletionDate: "2026-07-15",
    status: "In Progress",
    notes:
      "Structure mounting is complete. Solar panels are currently being mounted on Phase 2 roof.",
    documents: [
      {
        name: "struct_design_final.pdf",
        url: "#",
        category: "Structure Design",
      },
      { name: "net_meter_noc.pdf", url: "#", category: "NOC Approval" },
    ],
    timeline: [
      {
        status: "New",
        title: "Project Registered & Financed",
        date: "2026-04-10",
        done: true,
      },
      {
        status: "Assigned",
        title: "Assigned to Waaree Green Energy",
        date: "2026-05-01",
        done: true,
      },
      {
        status: "In Progress",
        title: "Site Inspection & Materials Delivered",
        date: "2026-05-15",
        done: true,
      },
      {
        status: "In Progress",
        title: "Mounting Structure Installation",
        date: "2026-05-28",
        done: true,
      },
      {
        status: "Installation Scheduled",
        title: "Inverter Wiring & Panel Mounting",
        date: "2026-06-15",
        done: false,
      },
      {
        status: "Completed",
        title: "Discom Net Metering & Commissioning",
        date: "2026-07-15",
        done: false,
      },
    ],
  },
  {
    id: "proj-2",
    projectName: "Goel Resident Rooftop Solar System",
    customerName: "Rajesh Goel",
    projectType: "Residential",
    kwSize: 8,
    location: "Salt Lake Sec-3, Kolkata",
    state: "West Bengal",
    district: "Kolkata",
    cluster: "East Cluster-A",
    installationAddress:
      "FE Block, House 341, Salt Lake Sector 3, Kolkata 700091",
    assignedEPCPartnerId: "epc-1",
    assignedEPCPartnerName: "Vikram Solar Solutions",
    assignedInstallerId: "inst-1",
    assignedInstallerName: "Subhasish Roy",
    startDate: "2026-06-01",
    expectedCompletionDate: "2026-06-20",
    status: "In Progress",
    notes:
      "Residential net-meter application filed with WBSEDCL. Structure completed today.",
    documents: [
      { name: "site_inspection_form.pdf", url: "#", category: "Site Survey" },
    ],
    timeline: [
      {
        status: "New",
        title: "Booking Received & Discom Permitted",
        date: "2026-05-20",
        done: true,
      },
      {
        status: "Assigned",
        title: "Assigned to Vikram Solar Solutions",
        date: "2026-06-01",
        done: true,
      },
      {
        status: "In Progress",
        title: "Structure Assembled",
        date: "2026-06-08",
        done: true,
      },
      {
        status: "Installation Scheduled",
        title: "Installer Inspection Scheduled",
        date: "2026-06-12",
        done: false,
      },
      {
        status: "Completed",
        title: "Handover & App Setup",
        date: "2026-06-20",
        done: false,
      },
    ],
  },
  {
    id: "proj-3",
    projectName: "Century Textiles Warehousing Rooftop",
    customerName: "Century Textiles & Ind.",
    projectType: "Industrial",
    kwSize: 500,
    location: "Whitefield Industrial Area",
    state: "Karnataka",
    district: "Bengaluru Urban",
    cluster: "South Cluster-A",
    installationAddress: "Plot 42-A, Road No 3, Whitefield, Bengaluru 560066",
    assignedEPCPartnerId: "epc-4",
    assignedEPCPartnerName: "Renewable Power Point",
    assignedInstallerId: "inst-2",
    assignedInstallerName: "Suresh Kumar",
    startDate: "2026-05-10",
    expectedCompletionDate: "2026-08-30",
    status: "In Progress",
    notes:
      "Structural safety clearance received from BBMP. Procurement of 500KW mono-PERC items initiated.",
    documents: [
      {
        name: "struc_safety_clearance.pdf",
        url: "#",
        category: "BBMP Clearance",
      },
    ],
    timeline: [
      {
        status: "New",
        title: "Industrial Application Approved",
        date: "2026-04-20",
        done: true,
      },
      {
        status: "Assigned",
        title: "Partner Selected & Onboarded",
        date: "2026-05-10",
        done: true,
      },
      {
        status: "In Progress",
        title: "Structural Civil Foundations",
        date: "2026-06-03",
        done: true,
      },
      {
        status: "In Progress",
        title: "Vanguard Mounting Rails Setup",
        date: "2026-06-25",
        done: false,
      },
      {
        status: "Completed",
        title: "500KW Commissioning Verification",
        date: "2026-08-30",
        done: false,
      },
    ],
  },
  {
    id: "proj-4",
    projectName: "Mehta Bungalow Solarization Pro",
    customerName: "Nimesh Mehta",
    projectType: "Residential",
    kwSize: 12,
    location: "Ghatkopar East, Mumbai",
    state: "Maharashtra",
    district: "Mumbai Suburban",
    cluster: "West Cluster-B",
    installationAddress:
      "Vikrant Circle, Vallabh Baug Lane, Ghatkopar, Mumbai 400077",
    assignedEPCPartnerId: "",
    assignedEPCPartnerName: "Unassigned",
    assignedInstallerId: "",
    assignedInstallerName: "Unassigned",
    startDate: "",
    expectedCompletionDate: "2026-07-10",
    status: "New",
    notes:
      "Newly approved booking. Awaiting auto-qualification allocation rules matching or manual assignment.",
    documents: [],
    timeline: [
      {
        status: "New",
        title: "Consumer Booking Verified",
        date: "2026-06-09",
        done: true,
      },
      {
        status: "Assigned",
        title: "Awaiting Active EPC Partner Selection",
        date: "",
        done: false,
      },
    ],
  },
  {
    id: "proj-5",
    projectName: "Marwar Agro Cold Storage Off-Grid",
    customerName: "Marwar Agro Cooperative",
    projectType: "Industrial",
    kwSize: 320,
    location: "Jodhpur Suburbs",
    state: "Rajasthan",
    district: "Jodhpur",
    cluster: "North Cluster-D",
    installationAddress:
      "National Highway 112, Outskirts Jaipur-Jodhpur Link, Rural Rajasthan",
    assignedEPCPartnerId: "",
    assignedEPCPartnerName: "Unassigned",
    assignedInstallerId: "",
    assignedInstallerName: "Unassigned",
    startDate: "",
    expectedCompletionDate: "2026-09-15",
    status: "New",
    notes:
      "Agro cold storage requires off-grid batteries. Solon Solar (Rajasthan) was suspended, hence need a new qualified partner.",
    documents: [],
    timeline: [
      {
        status: "New",
        title: "Project Listed after Solon Suspension",
        date: "2026-06-10",
        done: true,
      },
    ],
  },
];

export const initialProducts = [
  {
    id: "prod-1",
    image: "panel",
    productName: "Vikram Solar Mono-PERC 540Wp",
    category: "Solar Panel",
    brand: "Vikram Solar",
    modelNumber: "VS-SOMERA-540",
    kwCapacity: "0.54",
    price: 185,
    stockQuantity: 1250,
    warranty: "12 Years Product, 25 Years Output",
    status: "In Stock",
    description:
      "High efficiency multi-busbar mono-crystalline silicon module with excellent micro-crack resistance.",
  },
  {
    id: "prod-2",
    image: "inverter",
    productName: "Sungrow On-Grid String Inverter 50kW",
    category: "Inverter",
    brand: "Sungrow Power",
    modelNumber: "SG50CX-V11",
    kwCapacity: "50",
    price: 1250,
    stockQuantity: 42,
    warranty: "5 Years Standard",
    status: "In Stock",
    description:
      "Smart commercial properties string inverter with 5 tracking inputs, IP66 protection, and active grid support.",
  },
  {
    id: "prod-3",
    image: "battery",
    productName: "Waaree Li-FePO4 Battery Pack 5kWh",
    category: "Battery",
    brand: "Waaree Energies",
    modelNumber: "W-LFP-5000",
    kwCapacity: "5",
    price: 1450,
    stockQuantity: 8,
    warranty: "7 Years Replacement",
    status: "Low Stock",
    description:
      "Smart lithium iron phosphate battery with advanced BMS, deep cycle discharge capabilities, and wall installation support.",
  },
  {
    id: "prod-4",
    image: "mounting",
    productName: "Vanguard Rustproof Alu-Structure 10kWp",
    category: "Mounting Structure",
    brand: "Vanguard Solar Rails",
    modelNumber: "V-AL-10",
    kwCapacity: "10",
    price: 280,
    stockQuantity: 110,
    warranty: "10 Years Mechanical",
    status: "In Stock",
    description:
      "Ductile aluminum profile rails designed to withstand wind gusts up to 150 km/h with high anodizing coating.",
  },
];

export const initialInstallers = [
  {
    id: "inst-1",
    installerName: "Subhasish Roy",
    epcPartnerId: "epc-1",
    epcPartnerName: "Vikram Solar Solutions",
    mobile: "+91 94321 09876",
    experienceYears: 6,
    skills: [
      "TIG Welding",
      "Rooftop Layout Design",
      "DC Cabling",
      "Safety Cert Audit",
    ],
    location: "Kolkata",
    projectTypesAllowed: ["Residential", "Commercial"],
    assignedProjectsCount: 2,
    availabilityStatus: "Available",
    rating: 4.7,
    documents: ["Aadhaar", "Solar Wiring Cert", "Sling Safety Lift Course"],
  },
  {
    id: "inst-2",
    installerName: "Suresh Kumar",
    epcPartnerId: "epc-4",
    epcPartnerName: "Renewable Power Point",
    mobile: "+91 80500 12345",
    experienceYears: 4,
    skills: [
      "Earthing Setup",
      "Inverter Interconnection",
      "Civil Foundation Concrete",
    ],
    location: "Bengaluru",
    projectTypesAllowed: ["Residential", "Commercial", "Industrial"],
    assignedProjectsCount: 4,
    availabilityStatus: "On Field",
    rating: 4.5,
    documents: ["Aadhaar", "PAN Card", "Electrical Supervisor License"],
  },
  {
    id: "inst-3",
    installerName: "Karan Patil",
    epcPartnerId: "epc-2",
    epcPartnerName: "Waaree Green Energy",
    mobile: "+91 90222 34567",
    experienceYears: 9,
    skills: [
      "HT Grid Sync",
      "Substation Automation",
      "Helioskop Modeling",
      "SCADA Setup",
    ],
    location: "Mumbai Suburban",
    projectTypesAllowed: ["Commercial", "Industrial", "Utility Scale"],
    assignedProjectsCount: 5,
    availabilityStatus: "On Field",
    rating: 4.9,
    documents: [
      "Aadhaar",
      "PG Diploma Renewable Energy",
      "First Responder First Aid",
    ],
  },
  {
    id: "inst-4",
    installerName: "Mahendra Beniwal",
    epcPartnerId: "epc-5",
    epcPartnerName: "Solon Solar Infrastructure",
    mobile: "+91 97812 34567",
    experienceYears: 3,
    skills: ["Residential Mounting", "Micro-inverter Config"],
    location: "Jaipur",
    projectTypesAllowed: ["Residential"],
    assignedProjectsCount: 0,
    availabilityStatus: "On Leave",
    rating: 4.1,
    documents: ["Aadhaar", "Technician Certification"],
  },
];

export const initialProjectOrderSettings = [
  {
    id: "pos-1",
    projectType: "Residential",
    minDaysBeforeInstallation: 5,
    maxDaysBeforeInstallation: 15,
    completionDateRangeDays: 10,
    calendarDateSelectionRules:
      "Exclude Sundays & National Holidays. Multi-slot scheduling enabled.",
    customerDateSelectionEnabled: true,
    isActive: true,
  },
  {
    id: "pos-2",
    projectType: "Commercial",
    minDaysBeforeInstallation: 10,
    maxDaysBeforeInstallation: 30,
    completionDateRangeDays: 25,
    calendarDateSelectionRules:
      "Subject to BBMP/MSEDCL Discom Feasibility NOC delivery timeline.",
    customerDateSelectionEnabled: true,
    isActive: true,
  },
  {
    id: "pos-3",
    projectType: "Industrial",
    minDaysBeforeInstallation: 15,
    maxDaysBeforeInstallation: 45,
    completionDateRangeDays: 60,
    calendarDateSelectionRules:
      "Structural Civil clearance from CEIG required before dates lock.",
    customerDateSelectionEnabled: false,
    isActive: true,
  },
  {
    id: "pos-4",
    projectType: "Utility Scale",
    minDaysBeforeInstallation: 30,
    maxDaysBeforeInstallation: 90,
    completionDateRangeDays: 120,
    calendarDateSelectionRules:
      "PPA signing schedule controls grid connection calendar triggers.",
    customerDateSelectionEnabled: false,
    isActive: true,
  },
];

export const initialOrderProcessSettings = [
  {
    id: "ops-1",
    projectType: "Residential",
    minKW: 1,
    maxKW: 10,
    region: "North, East, West",
    district: "All",
    cluster: "All Residents",
    orderProcessType: "Ecommerce Order",
    eligibleEPCPartnerTypes: ["New EPC Partner", "Experienced EPC Partner"],
    assignmentType: "Auto Assign",
    isActive: true,
  },
  {
    id: "ops-2",
    projectType: "Commercial",
    minKW: 10,
    maxKW: 100,
    region: "West, South",
    district: "Mumbai Suburban, Pune, Bengaluru Urban",
    cluster: "Metro Commercial Circles",
    orderProcessType: "Quote by EPC Order",
    eligibleEPCPartnerTypes: ["Experienced EPC Partner", "Premium EPC Partner"],
    assignmentType: "Manual Assign",
    isActive: true,
  },
  {
    id: "ops-3",
    projectType: "Industrial",
    minKW: 100,
    maxKW: 1000,
    region: "All States",
    district: "All",
    cluster: "Industrial Corridors",
    orderProcessType: "Bidding Order",
    eligibleEPCPartnerTypes: ["Premium EPC Partner", "Large Scale EPC Partner"],
    assignmentType: "Manual Assign",
    isActive: true,
  },
];

export const initialRatingBenefitRules = [
  {
    id: "rb-1",
    ratingRange: "4.7 - 5.0",
    extraProjectsAllowed: 10,
    priorityLevel: "High",
    discountBenefit: "3% Platform Fee Waiver, Lead Auto-push Priority",
    badgeName: "Solar Master",
    isActive: true,
  },
  {
    id: "rb-2",
    ratingRange: "4.3 - 4.6",
    extraProjectsAllowed: 5,
    priorityLevel: "Medium",
    discountBenefit: "1% Platform Fee Waiver, Periodic Quality Badging",
    badgeName: "Carbon Reducer",
    isActive: true,
  },
  {
    id: "rb-3",
    ratingRange: "4.0 - 4.2",
    extraProjectsAllowed: 2,
    priorityLevel: "Standard",
    discountBenefit: "Routine allocations based on location eligibility rules.",
    badgeName: "Certified Pro",
    isActive: true,
  },
];

export const initialEpcPartnerSettings = {
  minimumExperience: 2,
  minimumInstallersRequired: 3,
  requiredDocuments: [
    "Company Registration Certificate",
    "GST Certificate",
    "PAN Copy",
    "Bank Canceled Cheque",
    "Director / MD Identity Card",
    "ISO certification (Optional)",
  ],
  undertakingText:
    "We hereby undertake that all structural designs uploaded by our engineer on the EmergeSun Platform comply absolutely with National Building Code specifications, using quality-certified panels. We accept full statutory civil and electrical warranty obligations for 10 years of site running.",
  agreementTerms:
    "This Master Services Agreement is executed between EmergeSun Solar (Platform Owner) and the Approved EPC Partner. Approved Partners receive project bookings and direct customer escrow allocations. Partner pays a base platform fee percentage (Starter 5%, Growth 4%, Premium 3%, Enterprise 2%) per booked installation payout.",
  approvalWorkflow: "Single Step Admin",
  autoQualificationRulesEnabled: true,
  projectAssignmentRules:
    "Matches by Nearest HQ Location, capacity limit checks, subscription plan limits, and experience tier matching filters.",
};
